<?php

namespace DoctrineMongoODMModule\Hydrator;

use Doctrine\ODM\MongoDB\DocumentManager;
use Doctrine\ODM\MongoDB\Mapping\ClassMetadata;
use Doctrine\ODM\MongoDB\Hydrator\HydratorInterface;
use Doctrine\ODM\MongoDB\UnitOfWork;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ODM. DO NOT EDIT THIS FILE.
 */
class MetacopeMceditModelDocumentSheetModelHydrator implements HydratorInterface
{
    private $dm;
    private $unitOfWork;
    private $class;

    public function __construct(DocumentManager $dm, UnitOfWork $uow, ClassMetadata $class)
    {
        $this->dm = $dm;
        $this->unitOfWork = $uow;
        $this->class = $class;
    }

    public function hydrate($document, $data, array $hints = array())
    {
        $hydratedData = array();

        /** @Field(type="hash") */
        if (isset($data['title'])) {
            $value = $data['title'];
            $return = $value;
            $this->class->reflFields['title']->setValue($document, $return);
            $hydratedData['title'] = $return;
        }

        /** @Field(type="hash") */
        if (isset($data['description'])) {
            $value = $data['description'];
            $return = $value;
            $this->class->reflFields['description']->setValue($document, $return);
            $hydratedData['description'] = $return;
        }

        /** @Field(type="hash") */
        if (isset($data['keywords'])) {
            $value = $data['keywords'];
            $return = $value;
            $this->class->reflFields['keywords']->setValue($document, $return);
            $hydratedData['keywords'] = $return;
        }

        /** @Field(type="hash") */
        if (isset($data['indexfollow'])) {
            $value = $data['indexfollow'];
            $return = $value;
            $this->class->reflFields['indexfollow']->setValue($document, $return);
            $hydratedData['indexfollow'] = $return;
        }
        return $hydratedData;
    }
}