<?php

namespace DoctrineMongoODMModule\Hydrator;

use Doctrine\ODM\MongoDB\DocumentManager;
use Doctrine\ODM\MongoDB\Mapping\ClassMetadata;
use Doctrine\ODM\MongoDB\Hydrator\HydratorInterface;
use Doctrine\ODM\MongoDB\UnitOfWork;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ODM. DO NOT EDIT THIS FILE.
 */
class MetacopeMceditModelUserSheetModelHydrator implements HydratorInterface
{
    private $dm;
    private $unitOfWork;
    private $class;

    public function __construct(DocumentManager $dm, UnitOfWork $uow, ClassMetadata $class)
    {
        $this->dm = $dm;
        $this->unitOfWork = $uow;
        $this->class = $class;
    }

    public function hydrate($document, $data, array $hints = array())
    {
        $hydratedData = array();

        /** @Field(type="string") */
        if (isset($data['gender'])) {
            $value = $data['gender'];
            $return = (string) $value;
            $this->class->reflFields['gender']->setValue($document, $return);
            $hydratedData['gender'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['firstname'])) {
            $value = $data['firstname'];
            $return = (string) $value;
            $this->class->reflFields['firstname']->setValue($document, $return);
            $hydratedData['firstname'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['name'])) {
            $value = $data['name'];
            $return = (string) $value;
            $this->class->reflFields['name']->setValue($document, $return);
            $hydratedData['name'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['city'])) {
            $value = $data['city'];
            $return = (string) $value;
            $this->class->reflFields['city']->setValue($document, $return);
            $hydratedData['city'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['streetnr'])) {
            $value = $data['streetnr'];
            $return = (string) $value;
            $this->class->reflFields['streetnr']->setValue($document, $return);
            $hydratedData['streetnr'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['zipcode'])) {
            $value = $data['zipcode'];
            $return = (string) $value;
            $this->class->reflFields['zipcode']->setValue($document, $return);
            $hydratedData['zipcode'] = $return;
        }

        /** @EmbedOne */
        if (isset($data['coordinates'])) {
            $embeddedDocument = $data['coordinates'];
            $className = $this->unitOfWork->getClassNameForAssociation($this->class->fieldMappings['coordinates'], $embeddedDocument);
            $embeddedMetadata = $this->dm->getClassMetadata($className);
            $return = $embeddedMetadata->newInstance();

            $this->unitOfWork->setParentAssociation($return, $this->class->fieldMappings['coordinates'], $document, 'coordinates');

            $embeddedData = $this->dm->getHydratorFactory()->hydrate($return, $embeddedDocument, $hints);
            $embeddedId = $embeddedMetadata->identifier && isset($embeddedData[$embeddedMetadata->identifier]) ? $embeddedData[$embeddedMetadata->identifier] : null;

            $this->unitOfWork->registerManaged($return, $embeddedId, $embeddedData);

            $this->class->reflFields['coordinates']->setValue($document, $return);
            $hydratedData['coordinates'] = $return;
        }

        /** @Field(type="date") */
        if (isset($data['birthday'])) {
            $value = $data['birthday'];
            if ($value === null) { $return = null; } else { $return = \Doctrine\ODM\MongoDB\Types\DateType::getDateTime($value); }
            $this->class->reflFields['birthday']->setValue($document, clone $return);
            $hydratedData['birthday'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['phone'])) {
            $value = $data['phone'];
            $return = (string) $value;
            $this->class->reflFields['phone']->setValue($document, $return);
            $hydratedData['phone'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['fax'])) {
            $value = $data['fax'];
            $return = (string) $value;
            $this->class->reflFields['fax']->setValue($document, $return);
            $hydratedData['fax'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['teaminfo'])) {
            $value = $data['teaminfo'];
            $return = (string) $value;
            $this->class->reflFields['teaminfo']->setValue($document, $return);
            $hydratedData['teaminfo'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['mobile'])) {
            $value = $data['mobile'];
            $return = (string) $value;
            $this->class->reflFields['mobile']->setValue($document, $return);
            $hydratedData['mobile'] = $return;
        }
        return $hydratedData;
    }
}