<aside class="widget widget_nav_menu">
	<h3 class="widget-title">Top Destinations</h3>

	<div class="menu-top-destinations-container">
		<ul class="menu" id="menu-top-destinations">
			<li class="menu-item">
				<a href="destination-sub-page.html">London, England</a>
			</li>

			<li class="menu-item">
				<a href="destination-sub-page.html">Sydney, Australia</a>
			</li>

			<li class="menu-item">
				<a href="destination-sub-page.html">Chicago, USA</a>
			</li>

			<li class="menu-item">
				<a href="destination-sub-page.html">San Francisco, USA</a>
			</li>

			<li class="menu-item">
				<a href="destination-sub-page.html">Toronto, Canada</a>
			</li>

			<li class="menu-item">
				<a href="destination-sub-page.html">Buenos Aires, Argentina</a>
			</li>

			<li class="menu-item">
				<a href="destination-sub-page.html">Queenstown, New Zealand</a>
			</li>

			<li class="menu-item">
				<a href="destination-sub-page.html">Santorini, Greece</a>
			</li>
		</ul>
	</div>
</aside>